name: "GreenHexagon"
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_tts: ^4.2.3
  flutter_blue_plus: ^1.35.10
  permission_handler: ^12.0.1
  asset_fill: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/data/lesson/
    - assets/data/lesson/alphabet/
    - assets/data/lesson/basic_vocabulary/
    - assets/data/lesson/basic_vocabulary/lesson_1/
    - assets/data/lesson/basic_vocabulary/lesson_2/
    - assets/data/lesson/listening_exercise/
    - assets/data/lesson/speaking_exercise/
    - assets/data/sub_menu/
    - assets/icon/

flutter_launcher_icons:
  image_path: "assets/icon/logo_icon.png"
  android: true
  ios: true
  android_adaptive_icon:
    foreground_image: "assets/icon/logo_icon.png"
