final Map<String, Map<String, bool>> brailleMap = {
  "a": {"dot1": true, "dot2": false, "dot3": false, "dot4": false, "dot5": false, "dot6": false},
  "b": {"dot1": true, "dot2": true, "dot3": false, "dot4": false, "dot5": false, "dot6": false},
  "c": {"dot1": true, "dot2": false, "dot3": false, "dot4": true, "dot5": false, "dot6": false},
  "d": {"dot1": true, "dot2": false, "dot3": false, "dot4": true, "dot5": true, "dot6": false},
  "e": {"dot1": true, "dot2": false, "dot3": false, "dot4": false, "dot5": true, "dot6": false},
  "f": {"dot1": true, "dot2": true, "dot3": false, "dot4": true, "dot5": false, "dot6": false},
  "g": {"dot1": true, "dot2": true, "dot3": false, "dot4": true, "dot5": true, "dot6": false},
  "h": {"dot1": true, "dot2": true, "dot3": false, "dot4": false, "dot5": true, "dot6": false},
  "i": {"dot1": false, "dot2": true, "dot3": false, "dot4": true, "dot5": false, "dot6": false},
  "j": {"dot1": false, "dot2": true, "dot3": false, "dot4": true, "dot5": true, "dot6": false},
  "k": {"dot1": true, "dot2": false, "dot3": true, "dot4": false, "dot5": false, "dot6": false},
  "l": {"dot1": true, "dot2": true, "dot3": true, "dot4": false, "dot5": false, "dot6": false},
  "m": {"dot1": true, "dot2": false, "dot3": true, "dot4": true, "dot5": false, "dot6": false},
  "n": {"dot1": true, "dot2": false, "dot3": true, "dot4": true, "dot5": true, "dot6": false},
  "o": {"dot1": true, "dot2": false, "dot3": true, "dot4": false, "dot5": true, "dot6": false},
  "p": {"dot1": true, "dot2": true, "dot3": true, "dot4": true, "dot5": false, "dot6": false},
  "q": {"dot1": true, "dot2": true, "dot3": true, "dot4": true, "dot5": true, "dot6": false},
  "r": {"dot1": true, "dot2": true, "dot3": true, "dot4": false, "dot5": true, "dot6": false},
  "s": {"dot1": false, "dot2": true, "dot3": true, "dot4": true, "dot5": false, "dot6": false},
  "t": {"dot1": false, "dot2": true, "dot3": true, "dot4": true, "dot5": true, "dot6": false},
  "u": {"dot1": true, "dot2": false, "dot3": true, "dot4": false, "dot5": false, "dot6": true},
  "v": {"dot1": true, "dot2": true, "dot3": true, "dot4": false, "dot5": false, "dot6": true},
  "w": {"dot1": false, "dot2": true, "dot3": false, "dot4": true, "dot5": true, "dot6": true},
  "x": {"dot1": true, "dot2": false, "dot3": true, "dot4": true, "dot5": false, "dot6": true},
  "y": {"dot1": true, "dot2": false, "dot3": true, "dot4": true, "dot5": true, "dot6": true},
  "z": {"dot1": true, "dot2": false, "dot3": true, "dot4": false, "dot5": true, "dot6": true},
};
